"""Remote client configuration and transparent SSH proxying (v0.11.0).

Formalizes, inside the installed package itself, what used to require a
hand-maintained shell wrapper outside any repository: if this client's
config directory (see `config_dir()`) has a `client.toml` naming a remote
canonical Brain server, every `brain` invocation (other than a small set
of local-only commands) transparently re-execs itself over SSH against
that server instead of resolving a local vault — so installing this
package alone is enough to talk to a remote canonical Brain, with no
extra script to write or copy.

This client never trusts the system-wide SSH config (OSS note from
v0.10.1: a sandboxed caller can see a corrupted view of
`/etc/ssh/ssh_config.d/*`) — it always connects with `ssh -F` against a
brain-owned config generated by `brain setup`, which replaces rather than
supplements the system config entirely.

Identity selection (read vs. write key) is a client-side convenience only,
never a security boundary: the real enforcement is the server's own SSH
forced-command dispatcher, which refuses a write subcommand presented with
a read-only key regardless of what this module decides to try first.
"""
from __future__ import annotations

import os
import shlex
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from . import paths as paths_mod

CLIENT_CONFIG_ENV = "SAKO_BRAIN_CLIENT_CONFIG"
CONFIG_DIRNAME = paths_mod.APP_DIRNAME
SLUG = paths_mod.APP_DIRNAME

# Commands that must run locally even when a remote server is configured —
# they configure *this* client, or (for `init`) create a local vault; they
# are never something to hand to a remote canonical Brain.
LOCAL_ONLY_COMMANDS = {"setup", "integration", "init"}

# Mirrors the server dispatcher's WRITE_ONLY_SUBCOMMANDS / READ_ONLY_SUBCOMMANDS
# at the granularity the client can cheaply check. Getting this wrong picks
# the "wrong" key and gets a clear server-side refusal (or, for `project
# show`/`discover`/`sync` under a read-only-only setup, a spurious one) — it
# never grants or denies anything the server wouldn't enforce anyway.
_WRITE_TOP_LEVEL = {"decision", "update", "note", "handoff", "remember", "memory", "index"}
_PROJECT_READ_ONLY_SUBS = {"show", "discover", "sync"}


def _is_write_subcommand(argv: list[str]) -> bool:
    if not argv:
        return False
    top = argv[0]
    if top == "timeline":
        return len(argv) > 1 and argv[1] == "add"
    if top == "project":
        sub = argv[1] if len(argv) > 1 else None
        return sub not in _PROJECT_READ_ONLY_SUBS
    return top in _WRITE_TOP_LEVEL


@dataclass
class ClientConfig:
    server: str
    ssh_user: str
    ssh_port: str
    identity_file: str
    write_identity_file: str | None = None
    profile: str | None = None

    @property
    def effective_write_identity(self) -> str:
        return self.write_identity_file or self.identity_file


def config_dir() -> Path:
    base = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return base / CONFIG_DIRNAME


def client_config_path() -> Path:
    override = os.environ.get(CLIENT_CONFIG_ENV)
    if override:
        return Path(override).expanduser()
    return config_dir() / "client.toml"


def ssh_config_path() -> Path:
    return config_dir() / "ssh_config"


def ssh_known_hosts_path() -> Path:
    return config_dir() / "ssh_known_hosts"


def load_client_config(path: Path | None = None) -> ClientConfig | None:
    """None if no client config exists, or it exists but names no server
    (a purely local install — the common case and the default)."""
    p = path or client_config_path()
    if not p.is_file():
        return None
    with open(p, "rb") as fh:
        data = tomllib.load(fh)
    server = data.get("server")
    if not server:
        return None
    try:
        return ClientConfig(
            server=str(server),
            ssh_user=str(data.get("ssh_user", "brain")),
            ssh_port=str(data.get("ssh_port", "22")),
            identity_file=str(data["identity_file"]),
            write_identity_file=(str(data["write_identity_file"])
                                  if data.get("write_identity_file") else None),
            profile=(str(data["profile"]) if data.get("profile") else None),
        )
    except KeyError as exc:
        raise RemoteConfigError(
            f"{p} names a server but is missing required key {exc}. "
            "Re-run `brain setup` to regenerate it."
        ) from exc


class RemoteConfigError(RuntimeError):
    pass


def _host_alias(is_write: bool) -> str:
    return f"{SLUG}-write" if is_write else f"{SLUG}-read"


def render_ssh_config(cfg: ClientConfig, known_hosts: Path) -> str:
    """Strict, minimal, brain-owned SSH client config.

    Used with `ssh -F` — which *replaces*, not supplements, the system
    config (see `ssh(1)`) — so a corrupted or sandbox-virtualized view of
    `/etc/ssh/ssh_config.d/*` is never read at all. No host-key relaxation,
    no agent/X11/port forwarding, one dedicated known_hosts file this
    client owns and never shares with any other host.
    """
    common = f"""\
    HostName {cfg.server}
    Port {cfg.ssh_port}
    User {cfg.ssh_user}
    UserKnownHostsFile {known_hosts}
    GlobalKnownHostsFile /dev/null
    StrictHostKeyChecking yes
    CheckHostIP no
    ForwardAgent no
    ForwardX11 no
    PermitLocalCommand no
    BatchMode yes
    ConnectTimeout 10
"""
    return (
        f"# Generated by `brain setup` — do not edit by hand, re-run setup instead.\n"
        f"# Used with `ssh -F` so the system-wide SSH config is never consulted.\n"
        f"Host {_host_alias(False)}\n{common}"
        f"    IdentityFile {cfg.identity_file}\n"
        f"    IdentitiesOnly yes\n\n"
        f"Host {_host_alias(True)}\n{common}"
        f"    IdentityFile {cfg.effective_write_identity}\n"
        f"    IdentitiesOnly yes\n"
    )


def _toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_client_toml(cfg: ClientConfig) -> str:
    lines = [
        "# SAKO Brain client configuration — generated by `brain setup`.",
        "#",
        "# When `server` is set, every `brain` invocation (other than `setup`,",
        "# `integration`, and `init`) transparently proxies to it over a",
        "# restricted, forced-command SSH connection instead of resolving a",
        "# local vault. Delete this file (or comment out `server`) to fall back",
        "# to a purely local Brain, if one is configured.",
        "",
        f"server = {_toml_str(cfg.server)}",
        f"ssh_user = {_toml_str(cfg.ssh_user)}",
        f"ssh_port = {_toml_str(cfg.ssh_port)}",
        f"identity_file = {_toml_str(cfg.identity_file)}",
    ]
    if cfg.write_identity_file:
        lines.append(f"write_identity_file = {_toml_str(cfg.write_identity_file)}")
    if cfg.profile:
        lines.append(f"profile = {_toml_str(cfg.profile)}")
    return "\n".join(lines) + "\n"


def should_proxy(argv: list[str]) -> bool:
    """True if this invocation should transparently proxy to a remote
    canonical Brain rather than resolving a vault locally."""
    if not argv:
        return False
    first_positional = next((a for a in argv if not a.startswith("-")), None)
    if first_positional in LOCAL_ONLY_COMMANDS:
        return False
    if "--vault" in argv:
        return False
    if os.environ.get("BRAIN_ROOT") or os.environ.get("BRAIN_LOCAL"):
        return False
    try:
        cfg = load_client_config()
    except RemoteConfigError:
        # A broken client config must surface as a normal CLI error, not a
        # silent fall-through to local resolution (which would likely also
        # fail, but with a much more confusing message).
        return True
    return cfg is not None


def proxy_to_remote(argv: list[str]) -> int:
    """Re-exec as `ssh` against the configured canonical server, replacing
    this process entirely (stdin/stdout/stderr inherited as-is — required
    for `handoff write`'s stdin JSON and for interactive-shaped output).
    Never returns on success; raises/exits on a resolvable local problem."""
    cfg = load_client_config()
    if cfg is None:
        raise RemoteConfigError("internal: proxy_to_remote called with no remote configured")

    cfg_path = ssh_config_path()
    if not cfg_path.is_file():
        print(
            f"Error: {client_config_path()} names a remote server but "
            f"{cfg_path} (the brain-owned SSH config) does not exist. "
            "Re-run `brain setup`.",
            file=sys.stderr,
        )
        return 2

    is_write = _is_write_subcommand(argv)
    alias = _host_alias(is_write)
    remote_command = shlex.join(argv)

    ssh_argv = ["ssh", "-F", str(cfg_path), alias, "--", remote_command]
    os.execvp("ssh", ssh_argv)  # noqa: S606 — replaces this process; never returns
    return 127  # unreachable unless execvp itself fails to even start


def show_host_key(server: str, port: str) -> str:
    """`ssh-keyscan` output plus SHA256 fingerprints, for the user to verify
    out-of-band before trusting a new host — never trusted automatically."""
    scan = subprocess.run(
        ["ssh-keyscan", "-p", str(port), server],
        capture_output=True, text=True, timeout=15,
    )
    if scan.returncode != 0 or not scan.stdout.strip():
        raise RemoteConfigError(
            f"ssh-keyscan against {server}:{port} produced no host keys "
            f"({scan.stderr.strip() or 'no output'})."
        )
    lines = [ln for ln in scan.stdout.splitlines() if ln.strip() and not ln.startswith("#")]
    fingerprints = []
    for ln in lines:
        fp = subprocess.run(
            ["ssh-keygen", "-lf", "/dev/stdin"],
            input=ln + "\n", capture_output=True, text=True, timeout=5,
        )
        if fp.returncode == 0:
            fingerprints.append(fp.stdout.strip())
    report = "\n".join(lines) + "\n\nFingerprints (verify out-of-band before trusting):\n"
    report += "\n".join(fingerprints)
    return report
