"""Remote gateway configuration: this gateway's own public identity (its
canonical MCP resource URI) and where its OAuth state database lives.

Deliberately separate from `brain/paths.py`'s Config (the vault) and from
`brain/remote.py`'s ClientConfig (a desktop's SSH proxy config) — this is
a THIRD, distinct thing: the gateway is a server component with its own
SQLite database of OAuth clients/codes/tokens (never vault content, never
a vault path). It reaches canonical Brain exactly like any other client —
through `brain.mcp_bridge`, which in turn uses whatever this process's own
`brain setup` has configured (see `mcp_transport.py`) — so there is no
`vault_root` concept here at all; a gateway that could resolve a local
vault directly would bypass the server's own SSH-dispatcher authority,
which item 5/18 of the v0.12.0 task explicitly rules out.

Password hashing for the owner login lives in `owner_auth.py`, not here —
this module only decides the gateway's network identity and state
location.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit

from .. import paths as paths_mod

ENV_PREFIX = "BRAIN_GATEWAY_"


class GatewayConfigError(RuntimeError):
    pass


@dataclass
class GatewayConfig:
    canonical_uri: str    # e.g. "https://brain-mcp.example.com/mcp" — this gateway's own MCP endpoint
    db_path: Path
    host: str = "127.0.0.1"
    port: int = 8642

    @property
    def issuer(self) -> str:
        # The authorization server's issuer == the gateway's own origin
        # (resource server and authorization server co-located, which the
        # MCP authorization spec explicitly permits).
        parts = urlsplit(self.canonical_uri)
        return f"{parts.scheme}://{parts.netloc}"


def gateway_state_dir() -> Path:
    base = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local" / "state")
    return base / paths_mod.APP_DIRNAME / "remote-gateway"


def config_file_path() -> Path:
    override = os.environ.get(f"{ENV_PREFIX}CONFIG")
    if override:
        return Path(override).expanduser()
    base = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return base / paths_mod.APP_DIRNAME / "remote-gateway.toml"


def load_config() -> GatewayConfig:
    """Reads the gateway's own small TOML config. No secret lives in it —
    the owner credential and OAuth client secrets live in the database
    (`storage.py`), never in a config file."""
    import tomllib

    path = config_file_path()
    data: dict = {}
    if path.is_file():
        with open(path, "rb") as fh:
            data = tomllib.load(fh)

    canonical_uri = os.environ.get(f"{ENV_PREFIX}CANONICAL_URI") or data.get("canonical_uri")
    if not canonical_uri:
        raise GatewayConfigError(
            f"no canonical_uri configured — set it in {path} or {ENV_PREFIX}CANONICAL_URI "
            "(run `brain remote-gateway init --canonical-uri https://...` to generate this file)"
        )

    db_path = Path(data.get("db_path") or gateway_state_dir() / "gateway.db").expanduser()
    host = os.environ.get(f"{ENV_PREFIX}HOST") or data.get("host", "127.0.0.1")
    port = int(os.environ.get(f"{ENV_PREFIX}PORT") or data.get("port", 8642))

    return GatewayConfig(canonical_uri=canonical_uri, db_path=db_path, host=host, port=port)


def render_config_toml(canonical_uri: str, host: str | None = None, port: int | None = None) -> str:
    lines = [
        "# SAKO Brain remote gateway configuration — generated by",
        "# `brain remote-gateway init`.",
        "#",
        "# No secret lives in this file: the owner credential is in the",
        "# gateway's own database (see `brain remote-gateway set-owner-password`),",
        "# and OAuth client secrets are generated and stored there too.",
        "",
        f'canonical_uri = "{canonical_uri}"',
    ]
    if host:
        lines.append(f'host = "{host}"')
    if port:
        lines.append(f"port = {port}")
    return "\n".join(lines) + "\n"


def write_config(canonical_uri: str, host: str | None = None, port: int | None = None) -> Path:
    path = config_file_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_config_toml(canonical_uri, host, port), encoding="utf-8")
    paths_mod.ensure_private_file(path)
    return path
